#!/usr/bin/env python3
"""Validate Stage-5 source, campaign, fault-spec, patch, and monitor consistency.

This tool performs no simulation and never invokes Xcelium. It checks that:

1. The Stage-5 generator version and schema are known.
2. The campaign was generated by the current Stage-5 version.
3. Every campaign fault spec uses the same version and schema.
4. Fault-spec and campaign digests are internally consistent.
5. Stage-4 inputs and the immutable mapped netlist still match recorded SHA-256.
6. Generated monitors contain no unsupported final block or removed flush task.
7. Monitor manifests refer to the current campaign or fault specs.

A successful audit can produce a local Stage-5 version lock JSON.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence


STAGE5_CAMPAIGN_MARKER = "stage_05_fault_characterization_campaign"
STAGE5_FAULT_MARKER = "stage_05_fault_materialization"


class GuardError(RuntimeError):
    """Controlled version-guard failure."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def canonical_json_digest(value: Any) -> str:
    encoded = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def load_json(path: Path, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GuardError(f"{label} not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise GuardError(f"invalid {label} JSON {path}: {exc}") from exc

    if not isinstance(payload, dict):
        raise GuardError(f"{label} must contain one JSON object: {path}")

    return payload


def atomic_write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path = path.resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    text = json.dumps(
        payload,
        indent=2,
        sort_keys=False,
        ensure_ascii=False,
    ) + "\n"

    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def import_stage5_tool(path: Path) -> Any:
    path = path.resolve()

    if not path.is_file():
        raise GuardError(f"Stage-5 tool not found: {path}")

    spec = importlib.util.spec_from_file_location(
        "f2a_stage5_version_guard_target",
        path,
    )
    if spec is None or spec.loader is None:
        raise GuardError(f"cannot import Stage-5 tool: {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    if not hasattr(module, "PROGRAM_VERSION"):
        raise GuardError(f"Stage-5 tool has no PROGRAM_VERSION: {path}")
    if not hasattr(module, "SCHEMA_VERSION"):
        raise GuardError(f"Stage-5 tool has no SCHEMA_VERSION: {path}")

    return module


def resolve_reference(value: Any, base_dir: Path) -> Path:
    path = Path(str(value)).expanduser()
    if not path.is_absolute():
        path = base_dir / path
    return path.resolve()


def git_command(repo_root: Path, *arguments: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(repo_root), *arguments],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if completed.returncode != 0:
        raise GuardError(
            f"git command failed: git {' '.join(arguments)}\n"
            f"{completed.stderr.strip()}"
        )

    return completed.stdout.strip()


def check_recorded_file(
    *,
    record: Mapping[str, Any],
    path_key: str,
    sha_key: str,
    base_dir: Path,
    label: str,
    errors: list[str],
    checked_files: list[dict[str, Any]],
) -> None:
    raw_path = record.get(path_key)
    expected_sha = str(record.get(sha_key, ""))

    if not raw_path:
        errors.append(f"{label}: missing {path_key}")
        return

    path = resolve_reference(raw_path, base_dir)

    if not path.is_file():
        errors.append(f"{label}: file not found: {path}")
        return

    actual_sha = sha256_file(path)

    checked_files.append(
        {
            "label": label,
            "path": str(path),
            "sha256": actual_sha,
            "size_bytes": path.stat().st_size,
        }
    )

    if not expected_sha:
        errors.append(f"{label}: missing recorded SHA-256")
    elif actual_sha != expected_sha:
        errors.append(
            f"{label}: SHA-256 mismatch: "
            f"expected={expected_sha}, actual={actual_sha}"
        )


def audit_monitor(
    path: Path,
    errors: list[str],
) -> dict[str, Any]:
    path = path.resolve()

    record: dict[str, Any] = {
        "path": str(path),
        "exists": path.is_file(),
    }

    if not path.is_file():
        errors.append(f"monitor not found: {path}")
        return record

    text = path.read_text(encoding="utf-8", errors="strict")

    contains_final = bool(
        re.search(r"\bfinal\s+(?:begin|:)", text)
    )
    contains_removed_flush = bool(
        re.search(r"::flush\s*\(\s*\)\s*;", text)
    )
    contains_fflush = "$fflush" in text

    record.update(
        {
            "sha256": sha256_file(path),
            "size_bytes": path.stat().st_size,
            "contains_final_block": contains_final,
            "contains_removed_flush_task_call": contains_removed_flush,
            "contains_immediate_fflush": contains_fflush,
        }
    )

    if contains_final:
        errors.append(f"monitor contains unsupported final block: {path}")

    if contains_removed_flush:
        errors.append(f"monitor contains removed ::flush() call: {path}")

    if not contains_fflush:
        errors.append(f"monitor contains no immediate $fflush: {path}")

    return record


def audit_manifest(
    path: Path,
    *,
    campaign: Mapping[str, Any],
    campaign_path: Path,
    expected_schema: str,
    errors: list[str],
) -> dict[str, Any]:
    path = path.resolve()

    record: dict[str, Any] = {
        "path": str(path),
        "exists": path.is_file(),
    }

    if not path.is_file():
        errors.append(f"monitor manifest not found: {path}")
        return record

    payload = load_json(path, "monitor manifest")

    record.update(
        {
            "sha256": sha256_file(path),
            "size_bytes": path.stat().st_size,
            "kind": payload.get("kind"),
            "schema_version": payload.get("schema_version"),
        }
    )

    if str(payload.get("schema_version", "")) != expected_schema:
        errors.append(
            f"manifest schema mismatch {path}: "
            f"expected={expected_schema}, "
            f"actual={payload.get('schema_version')}"
        )

    recorded_campaign_digest = payload.get("campaign_digest_sha256")
    if recorded_campaign_digest is not None:
        expected_digest = campaign.get("campaign_digest_sha256")
        if recorded_campaign_digest != expected_digest:
            errors.append(
                f"manifest campaign digest mismatch {path}: "
                f"expected={expected_digest}, "
                f"actual={recorded_campaign_digest}"
            )

    recorded_campaign_path = payload.get("campaign")
    if recorded_campaign_path is not None:
        resolved_campaign = resolve_reference(
            recorded_campaign_path,
            path.parent,
        )
        if resolved_campaign != campaign_path.resolve():
            errors.append(
                f"manifest campaign path mismatch {path}: "
                f"expected={campaign_path.resolve()}, "
                f"actual={resolved_campaign}"
            )

    fault_spec_value = payload.get("fault_spec")
    fault_spec_digest = payload.get("fault_spec_digest_sha256")

    if fault_spec_value is not None:
        fault_spec_path = resolve_reference(
            fault_spec_value,
            path.parent,
        )

        if not fault_spec_path.is_file():
            errors.append(
                f"manifest fault spec not found {path}: "
                f"{fault_spec_path}"
            )
        else:
            fault_spec = load_json(
                fault_spec_path,
                "manifest fault spec",
            )
            actual_digest = fault_spec.get(
                "fault_spec_digest_sha256"
            )
            if fault_spec_digest != actual_digest:
                errors.append(
                    f"manifest fault-spec digest mismatch {path}: "
                    f"expected={actual_digest}, "
                    f"actual={fault_spec_digest}"
                )

    return record


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Audit Stage-5 generator, campaign, fault specs, "
            "patches, monitors, and manifests without simulation."
        )
    )

    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
    )
    parser.add_argument(
        "--tool",
        type=Path,
        default=None,
    )
    parser.add_argument(
        "--campaign",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--monitor",
        type=Path,
        action="append",
        default=[],
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        action="append",
        default=[],
    )
    parser.add_argument(
        "--report",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--write-lock",
        type=Path,
        default=None,
    )

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    repo_root = args.repo_root.resolve()
    campaign_path = args.campaign.resolve()

    tool_path = (
        args.tool.resolve()
        if args.tool is not None
        else (
            repo_root
            / "scripts"
            / "fault_characterization"
            / "stage5_faults.py"
        ).resolve()
    )

    errors: list[str] = []
    warnings: list[str] = []
    checked_files: list[dict[str, Any]] = []
    monitor_records: list[dict[str, Any]] = []
    manifest_records: list[dict[str, Any]] = []

    try:
        stage5_module = import_stage5_tool(tool_path)
        program_version = str(stage5_module.PROGRAM_VERSION)
        schema_version = str(stage5_module.SCHEMA_VERSION)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    try:
        git_head = git_command(repo_root, "rev-parse", "HEAD")
        git_branch = git_command(
            repo_root,
            "branch",
            "--show-current",
        )
        git_status = git_command(
            repo_root,
            "status",
            "--porcelain",
        )
    except GuardError as exc:
        errors.append(str(exc))
        git_head = ""
        git_branch = ""
        git_status = ""

    campaign: dict[str, Any] = {}
    spec_versions: Counter[str] = Counter()
    spec_schemas: Counter[str] = Counter()
    fault_count = 0
    patch_count = 0

    try:
        campaign = load_json(campaign_path, "Stage-5 campaign")
    except GuardError as exc:
        errors.append(str(exc))

    if campaign:
        if campaign.get("stage") != STAGE5_CAMPAIGN_MARKER:
            errors.append(
                f"campaign stage mismatch: {campaign.get('stage')!r}"
            )

        campaign_version = str(
            campaign.get("program_version", "")
        )
        campaign_schema = str(
            campaign.get("schema_version", "")
        )

        if campaign_version != program_version:
            errors.append(
                "campaign program-version mismatch: "
                f"tool={program_version}, campaign={campaign_version}"
            )

        if campaign_schema != schema_version:
            errors.append(
                "campaign schema-version mismatch: "
                f"tool={schema_version}, campaign={campaign_schema}"
            )

        expected_campaign_digest = canonical_json_digest(
            {
                "source_stage4": campaign.get("source_stage4"),
                "mapped_netlist": campaign.get("mapped_netlist"),
                "selected_sites": campaign.get("selected_sites"),
                "faults": campaign.get("faults"),
            }
        )
        actual_campaign_digest = campaign.get(
            "campaign_digest_sha256"
        )

        if actual_campaign_digest != expected_campaign_digest:
            errors.append(
                "campaign digest mismatch: "
                f"recorded={actual_campaign_digest}, "
                f"computed={expected_campaign_digest}"
            )

        source_stage4 = campaign.get("source_stage4")
        if isinstance(source_stage4, dict):
            check_recorded_file(
                record=source_stage4,
                path_key="candidates_path",
                sha_key="candidates_sha256",
                base_dir=campaign_path.parent,
                label="Stage-4 candidates",
                errors=errors,
                checked_files=checked_files,
            )
            check_recorded_file(
                record=source_stage4,
                path_key="selection_path",
                sha_key="selection_sha256",
                base_dir=campaign_path.parent,
                label="Stage-4 selection",
                errors=errors,
                checked_files=checked_files,
            )
        else:
            errors.append("campaign missing source_stage4 object")

        mapped_netlist = campaign.get("mapped_netlist")
        if isinstance(mapped_netlist, dict):
            check_recorded_file(
                record=mapped_netlist,
                path_key="path",
                sha_key="sha256",
                base_dir=campaign_path.parent,
                label="mapped netlist",
                errors=errors,
                checked_files=checked_files,
            )
        else:
            errors.append("campaign missing mapped_netlist object")

        faults = campaign.get("faults")
        if not isinstance(faults, list) or not faults:
            errors.append("campaign contains no faults")
            faults = []

        seen_fault_ids: set[str] = set()

        for record in faults:
            if not isinstance(record, dict):
                errors.append("campaign fault record is not an object")
                continue

            fault_id = str(record.get("fault_id", ""))

            if not fault_id:
                errors.append("campaign fault record has no fault_id")
                continue

            if fault_id in seen_fault_ids:
                errors.append(f"duplicate campaign fault ID: {fault_id}")
                continue

            seen_fault_ids.add(fault_id)
            fault_count += 1

            spec_value = record.get("fault_spec")
            patch_value = record.get("patch")

            if not spec_value:
                errors.append(f"{fault_id}: missing fault_spec path")
                continue

            spec_path = resolve_reference(
                spec_value,
                campaign_path.parent,
            )

            if not spec_path.is_file():
                errors.append(
                    f"{fault_id}: fault spec not found: {spec_path}"
                )
                continue

            spec = load_json(spec_path, f"fault spec {fault_id}")

            spec_version = str(spec.get("program_version", ""))
            spec_schema = str(spec.get("schema_version", ""))

            spec_versions[spec_version] += 1
            spec_schemas[spec_schema] += 1

            if spec.get("stage") != STAGE5_FAULT_MARKER:
                errors.append(
                    f"{fault_id}: fault-spec stage mismatch: "
                    f"{spec.get('stage')!r}"
                )

            if str(spec.get("fault_id", "")) != fault_id:
                errors.append(
                    f"{fault_id}: fault-spec ID mismatch: "
                    f"{spec.get('fault_id')!r}"
                )

            if spec_version != program_version:
                errors.append(
                    f"{fault_id}: program-version mismatch: "
                    f"tool={program_version}, spec={spec_version}"
                )

            if spec_schema != schema_version:
                errors.append(
                    f"{fault_id}: schema-version mismatch: "
                    f"tool={schema_version}, spec={spec_schema}"
                )

            computed_spec_digest = canonical_json_digest(
                {
                    key: value
                    for key, value in spec.items()
                    if key != "generated_at_utc"
                }
            )
            recorded_spec_digest = spec.get(
                "fault_spec_digest_sha256"
            )

            if recorded_spec_digest != computed_spec_digest:
                errors.append(
                    f"{fault_id}: fault-spec digest mismatch: "
                    f"recorded={recorded_spec_digest}, "
                    f"computed={computed_spec_digest}"
                )

            campaign_spec_digest = record.get(
                "fault_spec_digest_sha256"
            )
            if campaign_spec_digest != recorded_spec_digest:
                errors.append(
                    f"{fault_id}: campaign/spec digest mismatch: "
                    f"campaign={campaign_spec_digest}, "
                    f"spec={recorded_spec_digest}"
                )

            if not patch_value:
                errors.append(f"{fault_id}: missing patch path")
                continue

            patch_path = resolve_reference(
                patch_value,
                campaign_path.parent,
            )

            if not patch_path.is_file():
                errors.append(
                    f"{fault_id}: patch not found: {patch_path}"
                )
            elif patch_path.stat().st_size == 0:
                errors.append(
                    f"{fault_id}: patch is empty: {patch_path}"
                )
            else:
                patch_count += 1

    for monitor_path in args.monitor:
        monitor_records.append(
            audit_monitor(
                monitor_path,
                errors,
            )
        )

    if campaign:
        for manifest_path in args.manifest:
            manifest_records.append(
                audit_manifest(
                    manifest_path,
                    campaign=campaign,
                    campaign_path=campaign_path,
                    expected_schema=schema_version,
                    errors=errors,
                )
            )
    elif args.manifest:
        errors.append(
            "cannot validate monitor manifests without a valid campaign"
        )

    if git_status:
        warnings.append(
            "repository working tree is dirty; the lock records "
            "the exact Stage-5 tool SHA and git-status digest"
        )

    report = {
        "kind": "stage5_version_consistency_audit",
        "generated_at_utc": utc_now(),
        "status": "PASS" if not errors else "FAIL",
        "repository": {
            "root": str(repo_root),
            "branch": git_branch,
            "head": git_head,
            "working_tree_dirty": bool(git_status),
            "git_status_sha256": sha256_text(git_status),
            "git_status": git_status.splitlines(),
        },
        "stage5_tool": {
            "path": str(tool_path),
            "program_version": program_version,
            "schema_version": schema_version,
            "sha256": (
                sha256_file(tool_path)
                if tool_path.is_file()
                else None
            ),
        },
        "campaign": {
            "path": str(campaign_path),
            "exists": campaign_path.is_file(),
            "program_version": campaign.get("program_version"),
            "schema_version": campaign.get("schema_version"),
            "campaign_digest_sha256": campaign.get(
                "campaign_digest_sha256"
            ),
        },
        "fault_artifacts": {
            "fault_spec_count": fault_count,
            "patch_count": patch_count,
            "fault_spec_program_versions": dict(
                sorted(spec_versions.items())
            ),
            "fault_spec_schema_versions": dict(
                sorted(spec_schemas.items())
            ),
        },
        "checked_source_files": checked_files,
        "monitors": monitor_records,
        "manifests": manifest_records,
        "warnings": warnings,
        "errors": errors,
    }

    atomic_write_json(args.report.resolve(), report)

    if args.write_lock is not None:
        if errors:
            warnings.append(
                "version lock was not written because the audit failed"
            )
        else:
            lock = {
                **report,
                "kind": "stage5_version_lock",
                "lock_generated_at_utc": utc_now(),
            }
            atomic_write_json(args.write_lock.resolve(), lock)

    print()
    print("=" * 78)
    print("Fault2Assertion Stage-5 Version Consistency")
    print("=" * 78)
    print(f"Repository HEAD       : {git_head}")
    print(f"Stage-5 tool version  : {program_version}")
    print(f"Stage-5 tool schema   : {schema_version}")
    print(
        f"Campaign version      : "
        f"{campaign.get('program_version')}"
    )
    print(f"Fault specs checked   : {fault_count}")
    print(f"Patches checked       : {patch_count}")
    print(f"Monitors checked      : {len(monitor_records)}")
    print(f"Manifests checked     : {len(manifest_records)}")
    print(f"Warnings              : {len(warnings)}")
    print(f"Errors                : {len(errors)}")
    print(f"Audit report          : {args.report.resolve()}")
    print(f"Result                : {report['status']}")
    print("=" * 78)

    if warnings:
        print("\nWarnings:")
        for warning in warnings:
            print(f"  - {warning}")

    if errors:
        print("\nErrors:")
        preview_limit = 30
        for error in errors[:preview_limit]:
            print(f"  - {error}")
        if len(errors) > preview_limit:
            print(
                f"  ... {len(errors) - preview_limit} "
                "additional errors omitted"
            )

    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
